### ISSUE TITLE
NA-focused weekend gameplay events

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#106]
While players in the EU generally have enough players to run a good-sized game during their afternoon, players in the Americas generally have a harder time finding enough players for a decent game. 

With this in mind, I would like to propose adding event times for players to come online so that there is a good crowd to play with. This would not be particularly formal (at least for now), but might perhaps consist of certain gameplay modes for certain events or the like.

A time that might be doable is 7:00P PT/ 10:00P ET which should be possible for much of the NA community (may be somewhat late for Brazil and other eastern time zones however) which could be announced here and by use of server MOTDs if such an event can occur. 

Hopefully hosting events like this will help increase the NA crowd of players so that consistent games can be found without having to join early afternoon games like the current situation requires.

**Comment by qreeves** [comment]
A few regions may be a nice idea, what we need really is one person to coordinate each region and "host" the events by actually participating themselves.

**Comment by molexted** [comment]
There is a trial one planned tor 2am UTC, Sunday 26th May (which is the afternoon of Saturday the 25th in NA), for which I will bring back my server and change the MOTD for. There seemed to be support for some kind of special gameplay for each event, e.g. a gladiator event or an extra long survivor event or something. I'll have to arrange something every week for this if it proves to be popular.

**Comment by nonoesimposible** [comment]
Would it be possible, or even a good idea, to keep doing this event after RE2 is released? While hopefully there would be enough players to not require setting up a predetermined time, servers might be more full on event nights.

If enough people express interest, it could even be possible to arrange some sort of tournament or competition based on performance of players on event night.

**Comment by SteveHeist** [comment]
I fail to see why it couldn't continue to happen. A tournament might be difficult to set up just because of how RE2 servers "work", but at the same time it'd be doable.

**Comment by qreeves** [comment]
We'll probably keep doing them for a while, depending on interest, as they have been a good way to get people playing. I think they need predetermined times though, as they're only really "official" if one of the developers/etc are there playing.
