### ISSUE TITLE
Red Eclipse v1.6.0 (Sunset Edition)

### ISSUE THREAD

**Issue by qreeves** [redeclipse/world#12]
Red Eclipse v1.6.0 (Sunset Edition) has been released!

We apologize to everyone who downloaded **v1.5.9** and had to deal with its broken state. This release fixes those issues, and is dubbed "Sunset Edition", as this will be the final release with the old Cube Engine 2 rendering pipeline that we have used for the past *10 years*. In **v2.0** we will have an all new rendering system from **[Tesseract](http://tesseract.gg/)**, featuring dynamic lighting and other modern rendering techniques that are sure to impress everyone. Here's to another 10 years! :smile:

- Fixed broken release packages. Oops.
- Fixed memory leaks.
- Cleaned up some in-game messages.
- Created AppImage builds.
- Disabled sound when SDL 2.0.6 is detected as it is broken.
- Fix the random weapon selection code.
- Attempt to fix incorrect client state during desync.
- Limited the length of server descriptions to 80 characters.
- New maps, mapmodels, and vanity items have been added.
- Improved team balancing mechanics, including using statistics if available.
- Improved behaviour of reset-to-floor for flags/bombs/etc.

**Comment by acerspyro** [comment]
![image](https://user-images.githubusercontent.com/4400999/34285618-e02288ce-e6a8-11e7-9221-439d1fb1c5cf.png)
