### ISSUE TITLE
default edit texture colors

### ISSUE THREAD

**Issue by Dziq84** [redeclipse/world#124]
Actual colors of default edit textures are not working so good with lights (and eyes). When we open a new map - first we see dark blue texture (16m) which turns to WILD PURPLE after adding a sun with natural color (like 200 180 170). Second texture (8m) is too similiar in color terms.

I propose to change default texture colors to something more neutral. With that recolour, when you open a new map you will see CALM GREEN color, like grass field. Colors are still different for every texture but a bit less saturated - not hurting eyes in my opinion and better works with variety of coloured lights.  These starts with green, going to blueish, with two smaller ones as 'dark concrete color' and 'bricks'
Any thoughts?

original set:
![explorer_2019-09-12_02-15-12](https://user-images.githubusercontent.com/13541407/64744821-addceb00-d505-11e9-9c45-938433930c20.jpg)

my recolour:
![explorer_2019-09-12_02-15-30](https://user-images.githubusercontent.com/13541407/64744833-ba614380-d505-11e9-8d6f-3aae8a92941f.jpg)

**Comment by qreeves** [comment]
I mostly did it so they contrast, but I've got not problem changing them if everyone else is happy with it.

**Comment by Dziq84** [comment]
new colors are arrived in-game, feel free to feedback

**Comment by Jigoku** [comment]
Looks fine. Definitely better on the eyes i think.
