### ISSUE TITLE
Red Eclipse 2 launch schedule

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#133]
_Note: this is not a concrete schedule and some deadlines may be subject to modification._

Red Eclipse 2 launches on **Thursday, December 19th, 2019**. On this day the game will become freely available on Steam, and, of course, will continue to be available from the standard channels (like the website download). 

Leading up to this launch are some important deadlines to keep in mind when either contributing directly to the game or playtesting it:

### 1st November 
* Map release candidates are due for submission. The submission requirements are outlined in #127 for potential release maps.
* Any new vanities are due for submission. Since the quantity of vanities is not very important, it would be preferred for modelling effort to be redirected onto weapon models, ammo models, or animation/geometry work on the player.
* Weapon core mechanics will be set. This allows sounds and particles to have known requirements so they can be improved and refined without danger of being made redundant by changes. Weapon balance is not set in stone at this time (and will likely remain in flux until launch).
* Physics core mechanics will be set. No overhauling changes to weight/speed/impulse abilities of the player will be made, to allow for a sufficient window of playtest and map validation.
 
### 19th November
* Weapon release candidates are due for submission. This gives a month to make sure weapons are bug-free and satisfactory after they are presented.
* Ammo containers' release candidates are due for submission. If no submissions are recieved at this time, crappy programmer art *will* be procured.
* A trailer representing Red Eclipse 2 should be procured at this time, to allow its dissemination onto our sundry deep web marketing tactics.
* Maps at a fully refined stage and ready for merge pending bug checks.
* Steam achievements' decals submitted for integration.

### 1st December
* Feature freeze on all fronts, including UI, gamemode, and other additions  to the game.
* Pending unmerged weapon models or ammo models merged.
* Pending unmerged sound assets merged.
* Pending maps merged.
* At this time, the game should be considered complete. Playtesting and reporting any issues is greatly appreciated in this two-and-a-half week window prior to launch.

### 19th December
* RE2 launch on Steam.

**Comment by molexted** [comment]
November 1 has come and gone, and as such the following maps are currently planned to be the launch slate.

The eight maps for RE2:

## FFA Maps
### Auster
![auster](https://user-images.githubusercontent.com/23445929/68078447-fb056c80-fd92-11e9-98c4-372b81ec2bdf.png)
### Ennui
![ennui](https://user-images.githubusercontent.com/23445929/68078450-fb9e0300-fd92-11e9-94bd-87c9590409d5.png)
### Institute
![institute](https://user-images.githubusercontent.com/23445929/68078448-fb056c80-fd92-11e9-826c-adb80581ce70.png)\
### Trespass
![trespass](https://user-images.githubusercontent.com/23445929/68078453-fb9e0300-fd92-11e9-8b67-054885754140.png)

## Team Maps
### Fortitude
![fortitude](https://user-images.githubusercontent.com/23445929/68078451-fb9e0300-fd92-11e9-955c-7a03132390ed.png)
### Octavus
![octavus](https://user-images.githubusercontent.com/23445929/68078446-fb056c80-fd92-11e9-89b7-c302b71be579.png)
### Rift
![rift](https://user-images.githubusercontent.com/23445929/68078452-fb9e0300-fd92-11e9-91b0-21d8b8871011.png)

## Race Maps

### Cyanide
![cyanide](https://user-images.githubusercontent.com/23445929/68078480-939bec80-fd93-11e9-9a77-4b951df1bfe6.png)

**Comment by Calinou** [comment]
By the wayn I noticed the screenshots are distorted. Are these the ones taken by Red Eclipse automatically?

**Comment by molexted** [comment]
Yeah, they are, so the FOV is a bit unnatural in a square projection.
