### ISSUE TITLE
Pyramid pickup / collectible

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#139]
Here's a pickup item that could potentially be used for ammo collectibles;

It's a relatively simple stylised tetrahedron. SniperGoth helped to massively improve its appearance by making some nice AO's / normals to improve the texturing.

![20191117163047](https://user-images.githubusercontent.com/1535179/69010571-eb705100-0958-11ea-9003-50375a293c7b.png)
![20191117163407](https://user-images.githubusercontent.com/1535179/69010574-f1fec880-0958-11ea-8d38-6ae323a39a3f.png)
![20191117163508](https://user-images.githubusercontent.com/1535179/69010579-fa570380-0958-11ea-885e-05dde07dbd78.png)

Source files / model can be found below if anyone wanted to play about with it:
https://github.com/redeclipse/community/tree/master/unixfreak/models/pyramid/snipergoth-mod

**Comment by Calinou** [comment]
I like it :slightly_smiling_face: It reminds me of the ammo pickups in OpenArena.

**Comment by SteveHeist** [comment]
It's not necessarily something this game needs, because you're only managing at most two ammo types in 90% of gamemodes.

**Comment by q009** [comment]
The amount of ammo types a player carries doesn't detract any value from this.
The idea was to use a model other than the gun for ammo.

**Comment by SteveHeist** [comment]
Yeah, I was referring to the icon. The model itself I'm completely on board with. It looks nice and is uniform.

Icon isn't as pertinent to me because the weapon icons in-game are just the models shrunk down it looks like, so they don't really add any information that the color doesn't already convey.

**Comment by Jigoku** [comment]
@Calinou 
> Would it make sense to display the weapon icon in the middle of triangle? This may require enlarging the middle area a little so it's more visible.

Could have a go at that. Tried something similar at first with a glow mask of the weapon icons, but didn't turn out well at the time.

**Comment by qreeves** [comment]
The texture looks a bit "dirty" (flecks etc) and I'm wondering if it fits the aesthetic we're working towards, which tends to be cleaner.
