### ISSUE TITLE
Dummies

### ISSUE THREAD

**Issue by Minecraft-Beast101** [redeclipse/world#144]
I wonder if there is a way to make a sandbox map with bots who stand still so you can test the effectiveness of guns.

**Comment by pocak100** [comment]
You can do that with the `botabilities` variable.

**Comment by SniperGoth** [comment]
Yes, as pocak100 said, type `botabilities 0` to make them stop and not react to anything.
Or, if you wish to hit moving targets, but they don't react to your attacks, `botabilities 115` for a change.
And type `resetvars` to have everything back to normal.

**Comment by Minecraft-Beast101** [comment]
Closing this as it has been resolves. Cheers, Steve.
