### ISSUE TITLE
FOSDEM20 and Merch

### ISSUE THREAD

**Issue by Rafirzm** [redeclipse/world#148]
- Version and build:  V2.0
- Related discussion: Merchandising, stickers, and conference
- Observation: RE V2.0 Looks like it doesn't have a Merch store nor participate to any conference event in the open-source domain, maybe a store with t-shirt for devs and stickers for the public arena could be great.
- Expected result: Keeping the open-source core, having maybe some media like screenshot to download, a bit like https://play0ad.com/
- How to reproduce: Speak about RE V2.0 at a conference.

**Comment by molexted** [comment]
The `base` repository issues list is NOT for idle musings. Please restrict issues submitted there to reproducible game issues.

**Comment by Rafirzm** [comment]
> The `base` repository issues list is NOT for idle musings. Please restrict issues submitted there to reproducible game issues.

Ok nice thanks, will see human, this is not a real issue, mind it.
