### ISSUE TITLE
Linux Appimage still 1.6.0

### ISSUE THREAD

**Issue by JoshuaPettus** [redeclipse/world#150]
Hi,  

As of writing, the download link for the linux app image still says 1.6.0 sunset edition when downloaded and launched. Is this an oversite?

https://www.redeclipse.net/download/appimage

Unless you aren't done with the official app image yet?  If so I didn't see it mentioned that the download being offered is still the old one.

Thank-you!

**Comment by qreeves** [comment]
Try the most recent one from deploy, I'll have to look into the website issues when I get a chance.

https://github.com/redeclipse/deploy/releases

**Comment by qreeves** [comment]
Fixed, thanks for your report.
