### ISSUE TITLE
Question about modelock, and still being able to force mode change through commands

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#157]
I'm running a small editing/openvars server using these server vars:

```
sv_serverclients 16
sv_masterlock 0
sv_spawnlock 0
sv_spawneditlock 0
sv_serverspectators 0
sv_mapslock 0
sv_maphistory 0
sv_defaultmode 1 // edit
sv_modelockfilter 2 // $modebitediting
sv_rotatemuts 0
sv_rotatemode 0
sv_rotatemodefilter 2 // $modebitediting
sv_varslock 0
sv_voteinterm 2 // unanimous vote only
sv_botlimit 10
sv_autoadmin 0
```

The mode should be locked to editing only. If you connect and open the map vote menu, only editing is selectable as expected. 

However, if you type (with no auth priviledges):

```
/deathmatch <map>
```

The server accepts the request and forces the mode change, which seems to be ignoring the modelockfilter, why is that?. I wasn't sure if this was a bug, so i'm asking here first in case something is incorrectly set/overlooked with the server config.

Ideally i just want to keep the server locked to editing mode.

**Comment by qreeves** [comment]
Will have to look into this, could be a regression.

**Comment by Jigoku** [comment]
Seems fine actually, i've just noticed i misunderstood the usage of `sv_masterlock 0`.

My intention was to allow anyone to claim `/setmaster 1`, however seems masterlock isn't actually used for that. I ended up setting `sv_masterlock 3`, which solves this issue, and restricts mode changes as expected when mutslock / modelock is set.

Not a bug, just me misconfiguration the servinit. :smile:

**Comment by qreeves** [comment]
Ah yeah, you're after `mastermode`
