### ISSUE TITLE
Small changes to the parkour challenge maps

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#162]
Made some small changes/detail to the challenge-port* maps. I'll post this here, but can open a PR if necessary.

* Increased the start/end corridor dimensions (they are way too small currently)
* Use consistent portal texture across the 5 maps
* Add mild vscroll to the portal texture
* Add geometry frame/detail to portals

The levels themselves have not changed, it's only a few tweaks to the start/end sections where the checkpoints/spawn are placed.

Download zip: 
[challenges-port-fix.zip](https://github.com/redeclipse/world/files/4177846/challenges-port-fix.zip)

![20200209211838](https://user-images.githubusercontent.com/1535179/74110164-1a761780-4b82-11ea-865b-eff7aa00eca8.png)

![20200209211819](https://user-images.githubusercontent.com/1535179/74110163-18ac5400-4b82-11ea-918c-843468c96d19.png)

**Comment by Jigoku** [comment]
Also there's an addition 6th one (remixed port4, changed the obstacle)

**Comment by Jigoku** [comment]
Also there's an additional 6th one here (chain-vaulting obstacle)
[challenges-port6.zip](https://github.com/redeclipse/world/files/4182556/challenges-port6.zip)

**Comment by qreeves** [comment]
You gonna PR this?

**Comment by Jigoku** [comment]
done :+1:
