### ISSUE TITLE
Segfault on rpi4 . S3tc???

### ISSUE THREAD

**Issue by Askmewho** [redeclipse/world#164]
Hi! Ive compiled master. Also, enabled 16 arb texture units on mesa (we have 2.1 desktop profile). Right now I cant use s3tc on mesa (I mean, by software, the hardware isnt capable and mesa wont do it on soft) . I suppose thats why its crashing on startup (it loads all the stuff and then it crash)
 If you do t use s3tc it may be something different.. then I would make a debug with gdb.

**Comment by qreeves** [comment]
_Moved to `world` as `base` is for confirmed bug reports, not support requests._

The engine will only use S3TC if the driver reports `GL_EXT_texture_compression_s3tc` is available. It will fall back to `GL_EXT_texture_compression_dxt1`, `GL_ANGLE_texture_compression_dxt3`, or `GL_ANGLE_texture_compression_dxt5` for this.

That being said, a Raspberry Pi 4 does not meet the system requirements for the game, and as such, we are unable to provide support for this use outside the scope of the project. Note that we only use the [Tesseract](http://tesseract.gg/) engine, we don't make it ourselves.

**Comment by Askmewho** [comment]
Mmm. Which requirements rpi4 does t meet?

**Comment by qreeves** [comment]
> **Graphics:** Intel HD 630 / Nvidia GeForce GT 630 / AMD Radeon HD 5750

As a project, we don't officially support Mesa rendering.

**Comment by Askmewho** [comment]
No mesa support 0.0 . Ok haha
