### ISSUE TITLE
Purge

### ISSUE THREAD

**Issue by dc-de** [redeclipse/world#169]
`Purge` is a re-light and ported version of the official Race map 'Purge' from Red Eclipse v1.6.
This map was original made by JoJo and was at last in Red Eclipse v1.6 official included in map rotation before it was excluded from the game since Red Eclipse 2.

**Purge** (New Version for Red Eclipse v2.0.1)
![purge](https://user-images.githubusercontent.com/60038236/96851602-7d7db500-1458-11eb-92d7-b4f9de8e92c1.png)

_Steps I done for the remix:_
- fixed blocks
- adjust and scale many block structures for a better gaming experience
- texture fixed and improved some places to look better and error correction
- reduce light elements and improved the old light settings
- I scale all the key elements up a bit to match the new game physics
- add a descriptions and optimize the map size and terrain around
- add rails and cameras
- and many other fixes of existing errors from the past versions

_Ideal Gameplay:_
race

**Current Version**
**_RE 2.0.1_**
**current latest version = r468**
[purge-r468.zip](https://github.com/redeclipse/world/files/5421781/purge-r468.zip)

_Steps left to be done for this maps:_
- [ ] Wait for mapshot fix because objekts on rails now hidden on mapshots
- [ ] Remove unneeded stuff and textures 
- [ ] Remove unneeded mapmodels

So watching out for bugs is always done with passion but sometimes I missed some :D
Feel free to inform me if you find some!

**Comment by Jigoku** [comment]
Good job with the scale, feels almost identical to 1.6 version as for size. :+1: 

Only small thing i noticed, is this part, 

![2020-03-09-133305_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/76217965-46c99600-620b-11ea-8690-4acdb80b7046.png)

when sliding under the, hud camera clips through geometry a bit, so probably good idea to move them up a little bit higher.

**Comment by dc-de** [comment]
yes, I should put it a bit higher again its too hard now for some player to pass it under.

**Comment by dc-de** [comment]
**Updated to r350**
- place mapshot camera
- massive texture fix from the original version
- rescale or textures
- place cams and rails
- improve geo
- improve lights and sound
- reduce cfg size
- texturecull

**Comment by dc-de** [comment]
I need some reviews to continue working on it!
Some feedback will be nice.

**Comment by qreeves** [comment]
Will get to it when I get to reviewing the maps for the 2.0.2 release.

**Comment by dc-de** [comment]
Purge really need a good platform on rails so "Crooked" started to made one for it.
[purge_platform_v0.1.zip](https://github.com/redeclipse/world/files/4434636/purge_platform_v0.1.zip)

But this platform now really need a good texture now fits with the purge map style, so if somebody like to do that feel free to go for it.
You can post your results here.

**Comment by dc-de** [comment]
**Updated to r392**
- improved camera rails
- more texture fixes
- rescale or textures
- place cams and rails
- mapmodel plattforms
- mopmodel cubes

**Comment by dc-de** [comment]
**Updated to r417**
- improved camera rails
- more texture fixes
- more mapmodel plattforms on rails
- more mopmodel cubes on rails
- placed anti parkour material

To do:
- [ ] Improve lights
- [ ] Add more cams on long rail track

More reviews and advises are requested and really welcome!

**Comment by dc-de** [comment]
**Updated to r428**
- improved camera rails
- more texture fixes
- fix cfg and sky texture

**Comment by dc-de** [comment]
**Updated purge to r468**
- improved camera rails
- replace all textures
- removed unneeded parkour material
