### ISSUE TITLE
Nightvision postfx shader

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#174]
Screenshot:
![2020-05-01-211452_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/80838406-dfb7d480-8bf0-11ea-972e-d000e43d1bd4.png)

Video: https://streamable.com/ciu5sw
(clip doesn't do it justice, as the grain/noise messes with video compression)

Place this in `nightvision.cfg` and run `exec nightvision.cfg`
This will bind to N as a toggle key:

```
defvarp nightvision 0 0 1

bind N [ 
    nightvision (= $nightvision); 
    if ($nightvision) [ 
        setpostfx nv 
        fullbrightmodels 200
        fullbrightfocus 3
        sound 181 
        sound 209
    ][ 
        clearpostfx 
        fullbrightmodels 0
        fullbrightfocus 0
        sound 181 
        sound 239
    ]
]
```

Place the shader near the bottom of the file named `config/glsl/postfx.cfg`
```glsl
// night vision postfx shader
lazyshader 0 "nv" (fsvs) (fsps [
    color.rgb *= mod(texcoord0.y,2.0)/2.0;   
    float noiselevel = 0.5;
    float noise = rand(texcoord0 + vec2(float(millis)));
    float grey = dot(color.xyz, vec3(0.5, 0.5, 0.5));
    vec3 green = vec3(1.1, 3.0, 1.1);
    
    fragcolor = (vec4(grey*green, color.a) + noise * noiselevel);
][
    float rand(vec2 co) { return fract(sin(dot(co.xy, vec2(12.9898, 78.233)))*43758.5453); }
    uniform float millis;
])
```

**Comment by qreeves** [comment]
Hax 🤣

**Comment by qreeves** [comment]
Merged into main as of https://github.com/redeclipse/base/commit/c884a5e3b1f3502194bd94e5aefc601695e047b4
