### ISSUE TITLE
Incompatible Servers

### ISSUE THREAD

**Issue by RipperSkid** [redeclipse/world#178]
So i was playing RE and then i was gonna play a time trial but theres no servers for it i checked incompatible and its all there how do i fix this?

**Comment by SniperGoth** [comment]
Depends, which version you are playing?

**Comment by RipperSkid** [comment]
> Depends, which version you are playing?

2.0.0

**Comment by Calinou** [comment]
> But it says 2.0.1 on some servers but how?

This is because they're running a development version of the game. If you want to play it, you have to compile it yourself.

**Comment by q009** [comment]
> This is because they're running a development version of the game. If you want to play it, you have to compile it yourself.

You actually don't have to, if you have the game on Steam you can just switch over to the development branch in the game properties, in the beta tab.
