### ISSUE TITLE
Brink (WIP)

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#180]
### Brink

Still early work in progress as geometry is still being worked on/retextured in many places, most of the inside isn't done yet but i'll post the current state of this now; you can download it below to see if there's any problems with the layout, any feedback / criticism is welcome.

* **setting**
 a refuelling platform, on the edge of a cliffside next to the ocean
* **size**
 medium/large (depending on mode)
* **mode**
 ideal for 10-15 ffa / survivor
 (will hopefully add map-balanced team mode support eventually)
* **variants**
 mid day / moonlight

I won't add a todo / unfinished list of things yet, as it still needs more work. Note, bots will probably jump into the ocean often, as the aiclip and waypoints will need to be redone.
 
## Download 
**r725** - [brink.zip](https://github.com/redeclipse/world/files/5043587/brink.zip)
**r986** - [brink-r986.zip](https://github.com/redeclipse/world/files/5213341/brink-r986.zip)

(just place the zip folder in your local data folder, no need to extract)

![2020-08-07-210347_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/89687943-06c12900-d8f9-11ea-912f-b4e89f20097e.png)
![2020-08-07-210421_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/89687948-0759bf80-d8f9-11ea-8236-2de482eba91c.png)

**Comment by Calinou** [comment]
Looks great!

Unrelated to the map itself, but I noticed the water pattern is a bit too repetitive. Can we add a variable to change its scale or replace the texture with an higher-resolution variant that spans a larger area?

**Comment by Jigoku** [comment]
**Updated to r986**
* too many changes to list

still needs a some retexturing / geometry fixes / lighting fixes / materials

**Comment by Ulukai55** [comment]
Looking excellent! Very nice texture work, I love the orange accents you created. 
And those rock parties are shaped with a lot of care I can tell. Well done!
