### ISSUE TITLE
Retrowave race map.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#182]
A race map that is set in a very abstract, retrofuturistic/virtual-like theme, and uses a lot of md3 models to give it life, along with a lot of moving platforms and obstacles.
There is a bunch of leaps of faith, so be careful!

![Hnet-image (3)](https://user-images.githubusercontent.com/24359960/93719301-efac6280-fb57-11ea-8e8d-05bd3c88b3f6.gif)

![20200920150202](https://user-images.githubusercontent.com/24359960/93719123-fdadb380-fb56-11ea-958f-e0e05dd52799.png)
![20200920150218](https://user-images.githubusercontent.com/24359960/93719124-fe464a00-fb56-11ea-81b3-a3b2d82d00aa.png)
![20200920150229](https://user-images.githubusercontent.com/24359960/93719125-fe464a00-fb56-11ea-8915-6817b5ee9d89.png)
![20200920150246](https://user-images.githubusercontent.com/24359960/93719126-fedee080-fb56-11ea-85e4-9bfa08bdb236.png)
![Hnet com-image (1)](https://user-images.githubusercontent.com/24359960/93719336-4a45be80-fb58-11ea-9cca-ec0437b7bfb2.gif)

Alternate variant has no fog, and a brighter color pallete.
![Hnet-image (6)](https://user-images.githubusercontent.com/24359960/93719607-0eabf400-fb5a-11ea-8fa3-cf28d8926769.gif)

[retrowave.zip](https://github.com/redeclipse/world/files/5252403/retrowave.zip)

PS: This is RE 2.1 only, as it uses the rail entity system for the moving obstacles.

**Comment by Ulukai55** [comment]
Well look at that! Crazy effects! Definitely going to try this one. I like the atmosphere you created. Nice work.

**Comment by qreeves** [comment]
Needs a good music track to go with it lol.
