### ISSUE TITLE
Can't command bots to pass the ball to me in Bomber Ball Mode.

### ISSUE THREAD

**Issue by ghost** [redeclipse/world#189]
No command in 2.0.0 master 2978 windows.
![Screenshot 2020-12-11 13-05-26](https://user-images.githubusercontent.com/75789534/101865567-95003100-3bb1-11eb-8459-004ca237422e.png)

**Comment by qreeves** [comment]
Bots will automatically pass the bomb to the nearest human in bomber-ball, they won't attempt to hold on to it unless there's no human to pass to.

**Comment by tiger-zhangc** [comment]
There is no information about this in official sites and game help manual.Also bots usually not next to me,if they pass the ball to me, there will not say like "I will pass the ball to you."

**Comment by Dziq84** [comment]
there is a distinctive sound when any bot (or another player) passing the ball to you.  It's not sufficient? ;p
