### ISSUE TITLE
Automated Duel Tournament #1

### ISSUE THREAD

**Issue by shacknetisp** [redeclipse/world#2]
Let's have a duel tournament! But this time, it's automated. Scheduling problems have been an issue in previous tournaments, and the planned summer tournaments never got started, but I've put together a system that's already working and requires minimal coordination.

The tournament runs from December 15th through December 31st.

[Leaderboard and Current Tournament State](https://ghostsclan.zapto.org/tourney)
An IRC channel has been set up at `#re-tourney` on Freenode.

This first automated tournament is experimental, so offer any suggestions for improvements here or for future events.

_Server owners, see the servers section below if you can volunteer a Red Eclipse server for the tournament._

## How to Participate?
Play some duels on one of the servers listed [here](https://ghostsclan.zapto.org/retourney.php) while authenticated. Only games played from December 15th through December 31st will count in the ranking.

Before your games with an opponent are counted in the ranking, you must duel at least three times on a tournament server with them. All previous games with them (in the tournament) then become part of the ranking. So, basically, play three games or more games with each opponent and it'll count.

In order to qualify for the winner's position, you must play with at least two opponents, meaning that the minimum number of games to play for the tournament is six.

The mode is ffa-duel deathmatch, with optional hard & basic. Certain further mutators (instagib, kaboom, medieval, and gladiator) are split into separate rankings and leaderboards. Additional mutators beyond these will disqualify the game from being counted in the tournament.

[View the verbose criteria here](https://ghostsclan.zapto.org/tourney).

## Ratings
The ratings used to calculate the leaderboards are the players' Glicko-2 rating subtracted by the rating deviation. Play several games to stabilize your rating deviation so your true skill shows.

## Servers
[Servers you can play on are listed here](https://ghostsclan.zapto.org/tourney).

If you can volunteer a server for the tournament, contact me (Beha) to get your server set up for statistics recording. We need several servers in various geographical locations for the best results. The config I use for my tournament server is included, but any config will technically work though only qualifying games will be counted.

```
// Set serverport, serverauthkey, adminpass, etc.

// IRC nick suffix in #re-tourney.
C:IRCSUFFIX = snisp
// Additional serverdesc information.
C:DESC = "Snisp"
// Additional motd information.
C:MOTD = "Hosted by Beha, Northeast USA"

/// Optional settings.
// Keep demos of each game for 30 days.
sv_demoautoserversave 1
sv_demoserverkeeptime (* 60 60 24 30)

/// Below this line is the basic config.

sv_serverdesc (concat "Duel Tournament Server" "|" $C:DESC)
sv_servermotd (concat "Duel Tournament Server | https://ghostsclan.zapto.org/tourney | #re-tourney on Freenode" "|" $C:MOTD)

ircfilter 1
if (= $rehashing 0) [
        ircaddrelay main irc.freenode.net 6667 (concatword RETY "-" $C:IRCSUFFIX)
        ircaddchan main #re-tourney
        ircrelaychan main #re-tourney 3
        ircconnect main
]

// Allowed maps.
sv_mainmaps $sv_duelmaps
sv_allowmaps $sv_duelmaps

// Lock the queue.
sv_duelmaxqueued 2

// Higher varslock.
sv_varslock 5

// Lock modes and mutators.
sv_mapslock 5
sv_modelock 8
sv_modelockfilter $modebitdeathmatch
sv_mutslockforce ( + $mutsbitffa $mutsbitduel )
sv_mutslockfilter ( + $mutsbitffa $mutsbitduel $mutsbithard $mutsbitbasic $mutsbitgsp1 $mutsbitinstagib $mutsbitkaboom $mutsbitmedieval )
sv_rotatemodefilter $sv_modelockfilter
sv_defaultmuts ( + $sv_mutslockforce $mutsbithard $mutsbitbasic )
sv_rotatemutsfilter $sv_defaultmuts

// Let any previous map be used.
sv_maphistory 0
```

**Comment by shacknetisp** [comment]
The tournament has now begun. Good luck!

**Comment by shacknetisp** [comment]
The tournament has finished, and the winner (by playing with more than one person) is @acerspyro! Congratulations!

**Comment by acerspyro** [comment]
Thank you so much! I'm so happy I'm in tears 🥇 🥇 🥇
