### ISSUE TITLE
Cathedral of Pain (gladiator)

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#20]
My cathedral gladiator map, from 1.5, with ported to 1.9.9 .
Large-sized, with 2 floors.

Map description : "A cathedral of the Old World, where people come to see the madness of the restless Gladiators."

Night variant : 
![20180105102119](https://user-images.githubusercontent.com/24359960/34609493-21862e2c-f204-11e7-96c0-429d0b2b995b.png)
Im using the moving target model, to simulate people "passing by" the Windows.
This is only appears on the night variant.
![20180105102343](https://user-images.githubusercontent.com/24359960/34609520-3ee71c1a-f204-11e7-8809-271b9260fc72.png)
![20180105102349](https://user-images.githubusercontent.com/24359960/34609521-3f060364-f204-11e7-8f94-11914306d56f.png)

Day variant:
![20180105102312](https://user-images.githubusercontent.com/24359960/34609494-21a8b0fa-f204-11e7-84da-a373e7aee4c8.png)
![20180105102327](https://user-images.githubusercontent.com/24359960/34609566-7849419a-f204-11e7-9509-f7781bbe5824.png)

Map file : 
[cathedral.zip](https://github.com/red-eclipse/world/files/1606567/cathedral.zip)

**Comment by qreeves** [comment]
Nice to see some maps taking full advantage of the new variants 😄

**Comment by SniperGoth** [comment]
Ooh, you can be sure im going to port over all of my maps (gladiator and race) to REtess's standarts in the not so distant future, hahah

**Comment by nok-ko** [comment]
Very, very nice. I think the wall textures look a little bit wonky/repetitive, though.

**Comment by qreeves** [comment]
Now in master for testing purposes as of red-eclipse/base@8a3ec68e75e1296f19aad884668b6719f2712d91

**Comment by SniperGoth** [comment]
Hmn,  i better update it with other textures because of the errors then.

**Comment by qreeves** [comment]
Yeah, I fudged the textures to make it work in the repository, but feel free to work on your own version in this case, my modifications were only textures.

**Comment by SniperGoth** [comment]
Playing with some ideas... (ivy model, a dead tree model)

![20180817215609](https://user-images.githubusercontent.com/24359960/44294100-6fc0b980-a268-11e8-8652-8f7304515f8f.png)
![20180817215612](https://user-images.githubusercontent.com/24359960/44294101-70595000-a268-11e8-92eb-ac856b7aa0aa.png)
![20180817213720](https://user-images.githubusercontent.com/24359960/44294102-70595000-a268-11e8-8869-34de97eb141d.png)
![20180817213751](https://user-images.githubusercontent.com/24359960/44294103-70595000-a268-11e8-9ef7-0ca4ecd84e4b.png)
Not sure if  i will go with this direction. 
Opinions are appreciated.

**Comment by qreeves** [comment]
Not sure about the dead tree, there's too much of it but what is there is sparse, so it looks weird from certain angles. The ivy seems okay from the screenshots though.

**Comment by SniperGoth** [comment]
Heh, that dead tree model is sitting here for ages, thought i'd give it a shot and test it, but yeah, you're right, it looks a bit strange depending on the angle.

**Comment by SniperGoth** [comment]
More playing around.. time to start doing meshes (no textures/normal maps atm)!
 
![20180819161534](https://user-images.githubusercontent.com/24359960/44312305-63557180-a3cc-11e8-8258-bf61dd6ad91d.png)
![20180819161547](https://user-images.githubusercontent.com/24359960/44312306-67818f00-a3cc-11e8-9969-70810d416247.png)
![20180819161628](https://user-images.githubusercontent.com/24359960/44312307-69e3e900-a3cc-11e8-99d3-ecfa64478562.png)

**Comment by SniperGoth** [comment]
More stuff done!
Nothing textured.. yet. AO maps backed onto the UV's.

![20180824225112](https://user-images.githubusercontent.com/24359960/44613859-b8d8b680-a7f0-11e8-8332-a369ee904cca.png)
![20180824225331](https://user-images.githubusercontent.com/24359960/44613860-b8d8b680-a7f0-11e8-8796-4a69f7be6a5f.png)

**Comment by SniperGoth** [comment]
I've restarted development of the map, and here's the last screenshots i took of it.

![20190708151946](https://user-images.githubusercontent.com/24359960/60833176-13be9680-a194-11e9-921a-72ecf5d37031.png)
![20190708152216](https://user-images.githubusercontent.com/24359960/60833252-3a7ccd00-a194-11e9-9b9c-0332a69099d3.png)
![20190708152232](https://user-images.githubusercontent.com/24359960/60833253-3a7ccd00-a194-11e9-8537-c46aa0d45d2c.png)

The map is using this texture for it's general stone-looking theme (the flying buttress model uses it too) : https://texturehaven.com/tex/?t=sandstone_blocks_05 , the licensing of that texture and all of the ones in the website are cc0, so no worries for that side (you should all check them out).

**Comment by SniperGoth** [comment]
And so, the map is finished. For now, that is.

Day variant : 
![20190811150521](https://user-images.githubusercontent.com/24359960/62837787-0fc9dc80-bc4a-11e9-85af-d13860ccb967.png)
![20190811150556](https://user-images.githubusercontent.com/24359960/62837788-0fc9dc80-bc4a-11e9-9182-ecb32d82bd1a.png)
![20190811142125](https://user-images.githubusercontent.com/24359960/62837789-0fc9dc80-bc4a-11e9-800e-f37104252022.png)
![20190811150106](https://user-images.githubusercontent.com/24359960/62837790-10627300-bc4a-11e9-946a-d4ab81f90ed0.png)
![20190811150417](https://user-images.githubusercontent.com/24359960/62837791-10627300-bc4a-11e9-89c9-de2b64bdeb97.png)

Night variant : 


![20190811150600](https://user-images.githubusercontent.com/24359960/62837800-2bcd7e00-bc4a-11e9-8ccd-d3c6ffae74f8.png)
![20190811150355](https://user-images.githubusercontent.com/24359960/62837801-2c661480-bc4a-11e9-963c-785b11d2ddaa.png)
![20190811150412](https://user-images.githubusercontent.com/24359960/62837802-2c661480-bc4a-11e9-87f6-ef840b2ace67.png)


A known glitch, is that for some unknown reason, when you switch to the alternative (night) variant of the map, the cloudbox just refuses to load, and thus, you need to re-type it to fix it.
So it is advised to play the map on the daylight variant until this gets fixed.


[Map file, and textures .zip](https://github.com/red-eclipse/world/files/3490286/Map.file.and.textures.zip)

[cathedral model part 2.zip](https://github.com/red-eclipse/world/files/3490289/cathedral.model.part.2.zip)

[cathedral model part 1 .zip](https://github.com/red-eclipse/world/files/3490290/cathedral.model.part.1.zip)

**Comment by SniperGoth** [comment]
And so, it is finished... for now.
Most of the models got LODs, and custom collision for them.
Place the models on snipergoth/HERE for them to load in-game.
It was a long trip, but this was worth as a learning experience, for trying to deal with 3d models for level design.
Next time, it will be way easier and faster, that i can presume.
Anyway, good luck Gladiators!

Day variant :

![20191102224721](https://user-images.githubusercontent.com/24359960/68079333-b7c4f100-fdc6-11e9-88d5-04a28a632d07.png)
![20191102224807](https://user-images.githubusercontent.com/24359960/68079329-b72c5a80-fdc6-11e9-8969-ed938fe87de0.png)
![20191102224830](https://user-images.githubusercontent.com/24359960/68079330-b72c5a80-fdc6-11e9-91c7-b238bd9cc92c.png)
![20191102224926](https://user-images.githubusercontent.com/24359960/68079331-b72c5a80-fdc6-11e9-9ca0-b318cf24fee1.png)

Night variant: 

![20191102224729](https://user-images.githubusercontent.com/24359960/68079337-d88d4680-fdc6-11e9-832c-142effdae89b.png)
![20191102224834](https://user-images.githubusercontent.com/24359960/68079338-d88d4680-fdc6-11e9-89d3-5069afa82264.png)
![20191102224841](https://user-images.githubusercontent.com/24359960/68079339-d925dd00-fdc6-11e9-9cd9-629b8b9b63c3.png)
![20191102224915](https://user-images.githubusercontent.com/24359960/68079340-d925dd00-fdc6-11e9-8705-21e349aea733.png)

[cathedral2.zip](https://github.com/redeclipse/world/files/3801159/cathedral2.zip)
