### ISSUE TITLE
GPU Info is accessible by players and contains sensitive information

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/world#21]
The GPU information should not be visible to anyone below OP status, as it reveals sensitive information about the user's system configuration, such as the GPU driver and kernel versions currently in use.

Operators and up may use it for administrative purposes, but a regular user has no good reason to have access to this information except for stalking.

This fix needs to be back ported to the Stable branch.

### Should system information be limited to moderators?
[![](https://api.gh-polls.com/poll/01C36Y75X7HK3WW5H3GGER3TK5/Yes)](https://api.gh-polls.com/poll/01C36Y75X7HK3WW5H3GGER3TK5/Yes/vote)
[![](https://api.gh-polls.com/poll/01C36Y75X7HK3WW5H3GGER3TK5/No)](https://api.gh-polls.com/poll/01C36Y75X7HK3WW5H3GGER3TK5/No/vote)

**Comment by qreeves** [comment]
The information is considered useful when helping other users diagnose problems as the user isn't able to readily get the information and forward it in-game. It's not really private information in the strictest sense.

### Should system information be limited to moderators?
/poll "Yes" "No"
