### ISSUE TITLE
Spaceships and generic Mapmodels

### ISSUE THREAD

**Issue by SalatielSauer** [redeclipse/world#24]
_I hope I'm posting this in the right place_

I made some Mapmodels, among them are:
- Ladder
- Small light pole
- Mirror (it looks more like a window)
- Computer shelf
- 03 Spaceships

Here are some screenshots (1.9.9):

![20180110074644](https://user-images.githubusercontent.com/9287152/34771345-032fe2be-f5e3-11e7-8819-0c9ad85118f1.png)

![20180110074606](https://user-images.githubusercontent.com/9287152/34771385-34f530d8-f5e3-11e7-9ddc-7aac10c9f9b6.png)

![20180110074629](https://user-images.githubusercontent.com/9287152/34771400-408131ea-f5e3-11e7-813e-4beecde83ad9.png)

![20180110074658](https://user-images.githubusercontent.com/9287152/34771409-4744c596-f5e3-11e7-9c20-2044d764cc12.png)

![20180110074725](https://user-images.githubusercontent.com/9287152/34771420-4f1a46a6-f5e3-11e7-86d8-ace49f37a081.png)

![20180110075032](https://user-images.githubusercontent.com/9287152/34771447-658d2282-f5e3-11e7-82ce-db3447d995a7.png)

![20180110075732](https://user-images.githubusercontent.com/9287152/34771481-759f32d2-f5e3-11e7-8c9e-8c1e0fcaf73a.png)

![20180110074615](https://user-images.githubusercontent.com/9287152/34771523-98c3d5d8-f5e3-11e7-8b80-9bae84915471.png)

![20180110075901](https://user-images.githubusercontent.com/9287152/34772829-36719b54-f5e8-11e7-9ba7-776e24eeffee.png)

![20180110074742](https://user-images.githubusercontent.com/9287152/34772819-2ac8f838-f5e8-11e7-92c3-1ee333d1468d.png)

They are already finalized, but your feedback is welcome!.

Thanks to Dziq for helping me with some issues.

10/01/18: [data.zip](https://github.com/red-eclipse/world/files/1618953/data.zip)
12/03/18: [update by @molexted ](https://github.com/red-eclipse/world/files/1804938/salatiel.zip)

**Comment by IceflowRE** [comment]
Could you include the data, that we can try or use it ourself?

**Comment by Salatiel2** [comment]
@IceflowRE Yes sure, attachment added to topic :)

**Comment by Dziq84** [comment]
these ships can serve for nice background detail or fundamental level part, that fitting RE style a much.
And that stair/ladder thingy is interesting too

**Comment by molexted** [comment]
[salatiel.zip](https://github.com/red-eclipse/world/files/1804228/salatiel.zip)

Same assets, but with the normal maps for spaceships enabled and all assets converted to PNG (from lossy jpg; if actual sources could be provided that would be great) and is therefore about 10% larger. The screenshots in #42 use this pack, made into its own directory in /data (e.g. /data/salatiel)

The textures are all compressed by optipng.

**Comment by SalatielSauer** [comment]
Greetings @molexted, the original exported skins (png), including models in .blend, can be found here:
[source_spaceships.zip](https://github.com/red-eclipse/world/files/1804715/source_spaceships.zip)
I am not good with materials, so feel free to improve them

Good luck with your ctf13 map!

**Comment by molexted** [comment]
I updated the download in the above post to include the uncompressed skins. 

ctf13 is built entirely around these mapmodels; if I decide to merge it, these assets will be merged into the master branch with it. There does not appear to be any license issues with merging them, but I'd like to make sure you're ok with some or all of your assets being merged into the game.

The spaceship models are really nicely done, easily usable props, and we can always use more "mundane" mapmodels like desks, stairs, lamps, boxes, tools etc. since they're generally uncubeable. 

If you need help getting anything to work you are always welcome to ask me, @Dziq84  or @SniperGoth here on the forum or on IRC.

**Comment by SalatielSauer** [comment]
Thanks, good to know that you liked the models. And yes, feel free to use all of them in your projects, that would be really cool! :)

**Comment by Goldenbrain1** [comment]
That looks awesome, but i don't understand how to install it

**Comment by Dziq84** [comment]
these are already included in master version of game, these will NOT work with 1.6
