### ISSUE TITLE
varslock

### ISSUE THREAD

**Issue by JeffBobbo** [redeclipse/world#35]
It came to my attention today that varslock is default at 2, which is the rank of supporter.

Given that varslock allows you to change weapons, this should probably be much higher (I actually thought it was set to 4 or 5).

Perhaps now would be a good time to go over the lock variables to check things are sane before Steam (if that's happening, apparently it is?), for instance I've just noticed votelock is set to 3 (disallowing supporters to vote prevmaps, but they can change game behaviour).

**Comment by qreeves** [comment]
Fixed in redeclipse/base@2303da4e245a59e276e5c9f025e8a09e750bdf1a
