### ISSUE TITLE
abuset (r976)

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#36]
![20180204001731](https://user-images.githubusercontent.com/23445929/35775629-5fb761da-0941-11e8-879b-075c27a6318c.png)
![20180204001725](https://user-images.githubusercontent.com/23445929/35775630-5fd2ab52-0941-11e8-9a66-d7dd2a5e5e2f.png)
![20180204001717](https://user-images.githubusercontent.com/23445929/35775631-5fee1a72-0941-11e8-9cf4-942993b7f74c.png)
![20180204001628](https://user-images.githubusercontent.com/23445929/35775661-d2a7033a-0941-11e8-989f-caf593c25c88.png)

Screenshots are taken at 1280x1024, all settings maxed, G3220T/Haswell GT1 GPU (note fps)

13kt/16kv 75 entities 16 lights

r897:
[abuset.zip](https://github.com/red-eclipse/world/files/1680142/abuset.zip)

r919:
[abuset.zip](https://github.com/red-eclipse/world/files/1683771/abuset.zip)

r943:
[abuset.zip](https://github.com/red-eclipse/world/files/1688330/abuset.zip)

r964:
[abuset.zip](https://github.com/red-eclipse/world/files/1691343/abuset.zip)

r976:
[abuset.zip](https://github.com/red-eclipse/world/files/1692600/abuset.zip)

What this map intends to accomplish:
- Create a more immersive, detailed environment to play in
- Make parkour less ubiquitous but still required for good gameplay
- Establish a clean background so as not to stand out more than the players (not so busy as to make it difficult to see players)

What this map does not attempt to accomplish:
- Preserve exactly the same parkour oppertunities as the old version
- Allow for unlimited parkouring on all surfaces
- Retain playability on 1.6 vars

**A Note on RE 2.0**
2.0 will not be unequivocally better than 1.6, just as UT4 isn't unequivocally better than UT3 or Q3A isn't unequivocally better than Q1 or Q2. There is negative value in translating the 1.6 experience into 2.0: all you end up with is higher computational requirements with little change in the actual visual experience. For 2.0 to be a viable game in its own right, it has to be significantly more visually appealing to be worth the performance penalty, and that will come with necessary changes to how maps are structured and how the game is played. **If you want the 1.6 experience, then play 1.6, because it is the best platform possible on which to base those gameplay mechanics.**

**Comment by qreeves** [comment]
Now in master for testing purposes as of red-eclipse/base@8a3ec68e75e1296f19aad884668b6719f2712d91

**Comment by IceflowRE** [comment]
Clean design, i like it.
