### ISSUE TITLE
Rift (ctf13)

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#42]
![20190929180206](https://user-images.githubusercontent.com/23445929/65842865-4b486500-e2e3-11e9-8532-39d4680fa0ca.png)
![20190929180157](https://user-images.githubusercontent.com/23445929/65842866-4b486500-e2e3-11e9-9f64-9ba22f8926d9.png)
![20190929180148](https://user-images.githubusercontent.com/23445929/65842867-4b486500-e2e3-11e9-8114-13c501671fc6.png)

<hr>

![20190917124255](https://user-images.githubusercontent.com/23445929/65073953-b50e5980-d948-11e9-82ca-50e8578f42de.png)

![20190917123851](https://user-images.githubusercontent.com/23445929/65073793-6791ec80-d948-11e9-8ebd-263112b7e2d0.png)

<hr>

v1, r67:[ctf13.zip](https://github.com/red-eclipse/world/files/1733409/ctf13.zip) 2018-02-16
v2, r75:[ctf13.zip](https://github.com/red-eclipse/world/files/1761246/ctf13.zip) 2018-02-26
v3, r81:[ctf13.zip](https://github.com/red-eclipse/world/files/1765623/ctf13.zip) 2018-02-27
v4, r89:[ctf13.zip](https://github.com/red-eclipse/world/files/1769888/ctf13.zip) 2018-02-28

v5, r98:[ctf13.zip](https://github.com/red-eclipse/world/files/1773924/ctf13.zip) 2018-03-01
v6, r112:[ctf13.zip](https://github.com/red-eclipse/world/files/1779581/ctf13.zip) 2018-03-02
v7, r119:[ctf13.zip](https://github.com/red-eclipse/world/files/1783765/ctf13.zip) 2018-03-04
v8, r122:[ctf13.zip](https://github.com/red-eclipse/world/files/1787926/ctf13.zip) 2018-03-05
v9, r146:[ctf13.zip](https://github.com/red-eclipse/world/files/1791906/ctf13.zip) 2018-03-06
v10, r159:[ctf13.zip](https://github.com/red-eclipse/world/files/1804973/ctf13.zip) 2018-03-07
v11, r172:[ctf13.zip](https://github.com/red-eclipse/world/files/1813574/ctf13.zip) 2018-03-12
v12, r176:[ctf13.zip](https://github.com/red-eclipse/world/files/1818018/ctf13.zip) 2018-03-16
v13, r184:[ctf13.zip](https://github.com/red-eclipse/world/files/1821315/ctf13.zip) 2018-03-17
v14, r191:[ctf13.zip](https://github.com/red-eclipse/world/files/1822356/ctf13.zip) 2018-03-18
v15, r193:[ctf13.zip](https://github.com/red-eclipse/world/files/1823139/ctf13.zip) 2018-03-19
v16, r199:[ctf13.zip](https://github.com/red-eclipse/world/files/1832032/ctf13.zip) 2018-03-21
v17, r203:[ctf13.zip](https://github.com/red-eclipse/world/files/1840247/ctf13.zip) 2018-03-23
v18, r224:[ctf13.zip](https://github.com/red-eclipse/world/files/1845088/ctf13.zip) 2018-03-25
v19, r227:[ctf13.zip](https://github.com/red-eclipse/world/files/1846465/ctf13.zip) 2018-03-26
v20, r232:[ctf13.zip](https://github.com/red-eclipse/world/files/1850714/ctf13.zip) 2018-03-27
v21, r244:[ctf13.zip](https://github.com/red-eclipse/world/files/1858875/ctf13.zip) 2018-03-29

v22, r255:[ctf13.zip](https://github.com/red-eclipse/world/files/1866175/ctf13.zip) 2018-04-01 
v23, r275:[ctf13.zip](https://github.com/red-eclipse/world/files/1901378/ctf13.zip) 2018-04-11
v24, r282:[ctf13.zip](https://github.com/red-eclipse/world/files/1905922/ctf13.zip) 2018-04-12
v25, r288:[ctf13.zip](https://github.com/red-eclipse/world/files/1913969/ctf13.zip) 2018-04-15
v26, r295:[ctf13.zip](https://github.com/red-eclipse/world/files/1918179/ctf13.zip) 2018-04-16
v27, r307:[ctf13.zip](https://github.com/red-eclipse/world/files/1926685/ctf13.zip) 2018-04-18
v28, r313:[ctf13.zip](https://github.com/red-eclipse/world/files/1930794/ctf13.zip) 2018-04-19
v29, r324:[ctf13.zip](https://github.com/red-eclipse/world/files/1936683/ctf13.zip) 2018-04-22
v30, r350:[ctf13.zip](https://github.com/red-eclipse/world/files/1945520/ctf13.zip) 2018-04-24
v31, r360:[ctf13.zip](https://github.com/red-eclipse/world/files/1958550/ctf13.zip) 2018-04-29

v32, r370:[ctf13.zip](https://github.com/red-eclipse/world/files/1966057/ctf13.zip) 2018-05-01
v33, r381:[ctf13.zip](https://github.com/red-eclipse/world/files/1973302/ctf13.zip) 2018-05-03
v34, r390:[ctf13.zip](https://github.com/red-eclipse/world/files/1976379/ctf13.zip) 2018-05-04
v35, r400:[ctf13.zip](https://github.com/red-eclipse/world/files/1977296/ctf13.zip) 2018-05-05
v36, r410:[ctf13.zip](https://github.com/red-eclipse/world/files/1990329/ctf13.zip) 2018-05-09
v37, r420:[ctf13.zip](https://github.com/red-eclipse/world/files/1993612/ctf13.zip) 2018-05-10
v38, r430:[ctf13.zip](https://github.com/red-eclipse/world/files/1995984/ctf13.zip) 2018-05-11
v39, r440:[ctf13.zip](https://github.com/red-eclipse/world/files/1998186/ctf13.zip) 2018-05-12
v40, r450:[ctf13.zip](https://github.com/red-eclipse/world/files/1999067/ctf13.zip) 2018-05-13
v41, r460:[ctf13.zip](https://github.com/red-eclipse/world/files/1999095/ctf13.zip) 2018-05-13
v42, r471:[ctf13.zip](https://github.com/red-eclipse/world/files/2007648/ctf13.zip) 2018-05-15
v43, r490:[ctf13.zip](https://github.com/red-eclipse/world/files/2029472/ctf13.zip) 2018-05-22
v44, r500:[ctf13.zip](https://github.com/red-eclipse/world/files/2061438/ctf13.zip) 2018-05-31

v45, r510:[ctf13.zip](https://github.com/red-eclipse/world/files/2064708/ctf13.zip) 2018-06-01
v46, r520:[ctf13.zip](https://github.com/red-eclipse/world/files/2066744/ctf13.zip) 2018-06-03
v47, r530:[ctf13.zip](https://github.com/red-eclipse/world/files/2079033/ctf13.zip) 2018-06-06

v48, r540:[ctf13.zip](https://github.com/red-eclipse/world/files/2975604/ctf13.zip) 2019-03-17

v49, r550: [ctf13.zip](https://github.com/red-eclipse/world/files/3494232/ctf13.zip) 2019-08-12 
v50, r560: [ctf13.zip](https://github.com/red-eclipse/world/files/3514654/ctf13.zip) 2019-08-19
v51, r570: [ctf13.zip](https://github.com/red-eclipse/world/files/3518716/ctf13.zip) 2019-08-19
v52, r580: [ctf13.zip](https://github.com/red-eclipse/world/files/3523874/ctf13.zip) 2019-08-20
v53, r590: [ctf13.zip](https://github.com/red-eclipse/world/files/3548975/ctf13.zip) 2019-08-27
v54, r600: [ctf13.zip](https://github.com/red-eclipse/world/files/3557901/ctf13.zip) 2019-08-29

v55, r610: [ctf13.zip](https://github.com/redeclipse/world/files/3586980/ctf13.zip) 2019-09-07
v56, r620: [ctf13.zip](https://github.com/redeclipse/world/files/3587808/ctf13.zip) 2019-09-08
v57, r630: [ctf13.zip](https://github.com/redeclipse/world/files/3593578/ctf13.zip) 2019-09-09
v58, r640: [ctf13.zip](https://github.com/redeclipse/world/files/3603688/ctf13.zip) 2019-09-11
v59, r651: [ctf13.zip](https://github.com/redeclipse/world/files/3603798/ctf13.zip) 2019-09-11
v60, r660: [ctf13.zip](https://github.com/redeclipse/world/files/3608418/ctf13.zip) 2019-09-12
v61, r670: [ctf13.zip](https://github.com/redeclipse/world/files/3611722/ctf13.zip) 2019-09-13
v62, r682: [ctf13.zip](https://github.com/redeclipse/world/files/3613513/ctf13.zip) 2019-09-15
v63, r690: [ctf13.zip](https://github.com/redeclipse/world/files/3614455/ctf13.zip) 2019-09-15
v64, r700: [ctf13.zip](https://github.com/redeclipse/world/files/3615301/ctf13.zip) 2019-09-16
v65, r710: [ctf13.zip](https://github.com/redeclipse/world/files/3618358/ctf13.zip) 2019-09-16
v66, r720: [ctf13.zip](https://github.com/redeclipse/world/files/3623101/ctf13.zip) 2019-09-17
v67, r730: [ctf13.zip](https://github.com/redeclipse/world/files/3638436/ctf13.zip) 2019-09-20
v68, r740: [ctf13.zip](https://github.com/redeclipse/world/files/3639464/ctf13.zip) 2019-09-22
v69, r750: [ctf13.zip](https://github.com/redeclipse/world/files/3640497/ctf13.zip) 2019-09-22
v70, r760: [ctf13.zip](https://github.com/redeclipse/world/files/3644627/ctf13.zip) 2019-09-23
v71, r770: [ctf13.zip](https://github.com/redeclipse/world/files/3650947/ctf13.zip) 2019-09-24
v72, r780: [ctf13.zip](https://github.com/redeclipse/world/files/3656123/ctf13.zip) 2019-09-25
v73, r790: [ctf13.zip](https://github.com/redeclipse/world/files/3663738/ctf13.zip) 2019-09-27
v74, r800: [ctf13.zip](https://github.com/redeclipse/world/files/3668410/ctf13.zip) 2019-09-29

#### Release Candidates

v75, **RC1** r805: [ctf13.zip](https://github.com/redeclipse/world/files/3668416/ctf13.zip) 2019-09-29
v76, **RC2** r810: [ctf13.zip](https://github.com/redeclipse/world/files/3672870/ctf13.zip) 2019-09-30

v77, **RC3** r815: [ctf13.zip](https://github.com/redeclipse/world/files/3679833/ctf13.zip) 2019-10-02
v78, **RC4** r820: [ctf13.zip](https://github.com/redeclipse/world/files/3692899/ctf13.zip) 2019-10-04
v79, **RC5** r825: [ctf13.zip](https://github.com/redeclipse/world/files/3722516/ctf13.zip) 2019-10-13
v80, **RC6** r847: [rift.zip](https://github.com/redeclipse/world/files/3882785/rift.zip) 2019-10-23

<hr>

Released under the WTFPL v2.

CTF map designed from the outset for 1.9.9 physics. It is a complete, finished map with pickups and affinities. It is partially asymmetrical in that the omega base has a larger hangar with a larger ship, and that different halves of the map have different decorations and non-accessible pathways.

It is one of the marquee maps for the upcoming RE2 launch.

Finding issues with the map (including clipping, texture, geometry, sound, pickups, and mapmodels) is appreciated at this stage, as they are all complete.

<hr>

 128m between end corridors of center atrium
 104m across center atrium
 90m across base chasms
~250m between bases
~12 seconds base to base
 2 of each weapon
 2 mines
 4 grenades

№ **(Δ)**
87 **(+0)** kilotriangles
120 **(+0)** kilovertices
693 **(+13)** entities
131 **(+0)** lights

**Comment by qreeves** [comment]
It is white 👍

**Comment by qreeves** [comment]
It's actually starting to look really good! 🥇

**Comment by jordaniancompress** [comment]
This is very cool

**Comment by Dziq84** [comment]
yeah, this is looking good :)

**Comment by qreeves** [comment]
Now in master for testing purposes as of red-eclipse/base@8a3ec68e75e1296f19aad884668b6719f2712d91
