### ISSUE TITLE
Increasing player scale from 1 to 1.25 or 1.3

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#51]
After working with 2.0 physics for a while and talking with other mappers ( @DonGeilo @SniperGoth @Dziq84)  we have all agreed that a slightly larger player scale would help alleviate some issues with current gameplay:

- The smaller hitbox makes it harder to hit players. Bigger players are obviously easier to hit than smaller ones.
- Players are larger relative to their parkour abilities, allowing corridors and rooms to be less cartoonishly large compared to the player's size (15m ceilings are kind of silly in real life but commonplace in RE maps) while not nerfing parkour itself (it's pretty hard to tell the difference in playerscale on an unfamiliar map)
- Players also are larger relative to props, meaning that Center's fire hydrants can be reasonably sized (as compared to man-sized) while not being puny toe-stubbing annoyances relative to gameplay speed.
- Doorways and corridors tend to be an even-number multiple of the cube grid (4x4m or 8x8m doors are normal), which means players are 1/4 or 1/2 as tall as the doors they go through. Making the playerscale equal to about three-fifths of a normal 4m door is much more proportional to reality (making the door 5/3rds as tall as the player is somewhere close to the height of a normal door, which is generally somewhere between 8/5ths and 4/3rds as tall as a typical person). While it is obviously possible to make the door e.g. 3x3 meters with current physics, this tends to require texture panning and scaling to look correct.

ctf13 is an example of a map which was designed around and works well with the playerscale set to 1.3.

**Comment by SniperGoth** [comment]
At first when this was proposed, i thought it was really strange, but after playing around with it, the general scale of the world seems more "realistic" and plausible, with the player being taller.
Right now, it just looks weird (see center and it's hydrants), so i give a 👍 for this.

**Comment by jamestonjes** [comment]
Personally I am all for this, this is a comparison shot of textures and models at default scale. 1.3 looks alot more realistic, not only would such a change make it easeir for people just picking up the editor to get a better sense of scale. It's also alot more practical than having to scale everything to something that doesnt play well with the grid, breaks up the sometimes weird feeling of the player being practically the same height as, or 2x or 1/2x of most textures.. sorry I don't mean to rant or anything, just legitimately think this is the way to go



![20180328234916](https://user-images.githubusercontent.com/8139282/38060581-419d0788-32e3-11e8-8f2c-832af5b376f5.png)
![20180328234904](https://user-images.githubusercontent.com/8139282/38060582-41b397a0-32e3-11e8-8ed7-a28a46cff75a.png)

**Comment by qreeves** [comment]
Will play around with this when I get back to working on the game code, though it'll be done more low-level than changing `playerscale`.

**Comment by qreeves** [comment]
Has everyone come to a consensus about how much to adjust the player size by?

**Which player size? (one week to respond)**

/polls 1.00x 1.05x 1.10x 1.15x 1.20x 1.25x 1.30x 1.35x 1.40x 1.45x 1.50x

**Comment by Dziq84** [comment]
1.32 seems ideal

**Comment by SniperGoth** [comment]
Hmn, maybe 1.25 because it fits the grid better.

**Comment by qreeves** [comment]
`1.32` might feel better because it would enlarge the area for hit detection, which is separate issue I'll be addressing once we've gotten everything else figured out (either by reverting to the old boxes, or artificially increasing the size of the model during the hitscan pass).

**Comment by Friedslick6** [comment]
I welcome the change, I always thought something was off about the original size.

And this isn't exactly feedback, but I wanted to attempt calculating this while taking anthropometry into consideration just for kicks:
- The average human height is [usually around 170cm](https://ourworldindata.org/human-height#the-last-two-millennia).
- I've estimated the smallest cube size at a real world scale to be 6.25cm, based on conjecture formed from estimated sizes of elements in textures previously used in Cube engine games (bricks, planks, etc.) and other's comparisons to Doom/Quake's Map Unit scale.
- The character height in the current stable build is approximately 16 cubes of the smallest size visually, so they're estimated real world height is ~100cm.
I think a 1.7x rescale would be the most "realistic", and yet entirely unrealistic in accommodating the maps and assets that have already been designed.

**Comment by qreeves** [comment]
We define it as `8 GL units = 1 metric meter`, so the player is now "2m" tall 😄

**Comment by Dziq84** [comment]
now when looking at default textures and it's sizes writen on these.. 1m looks like 0.5 for me, player have more than two meters now according o these textures. I know its too late.. but I think that player sizes should be even bigger to compared what we have now, and for example texture 2m should be 1m..  Damn its just too late.. now I found that old scale is better, just map models need rescaling.   ... :(

**Comment by Friedslick6** [comment]
The problem is two-fold.
Firstly, that the measurements currently printed on the default textures don't match their conversion to GL units:
If 8 GL units = 1m, then a 1-512th cube is .8 GL units or 10cm.
The 1m texture covers 8*8 1-512th cubes, and therefore actually represents 80cm.

Secondly, that there's two ways to interpret the height:
(On the premise of meeting the average human height of 170cm.)
Before:
* According to GL units, the height was 160cm and needed a x1.0625 upscale.
* According to the minimum height before crouching, the height was 151.25cm and needed a x1.1239669421487603305785 upscale.

After:
* According to GL units, the height is 200cm and needs a x1.1764705882352941 downscale.
* According to the minimum height before crouching, the height is 185cm and needs a x1.08823529411764705 downscale.

I'm not sure what the optimal player model height is, but I believe it requires reconsideration.

**Comment by molexted** [comment]
![20180613144119](https://user-images.githubusercontent.com/23445929/41379808-dcd3b678-6f17-11e8-8cfc-cac7ded78e23.png)
A size 1 cube is exactly 125mm or approximately 5 inches. A size 8 cube is exactly a meter. These sizes are not open to interpretation, because they are explicitly defined.

**Comment by Friedslick6** [comment]
I'm aware of their definition, and I don't think I was clear. The only point I wanted to make was that one's perceptions, such as thinking in 10s instead of 8s, could lead to misconception of the player's height despite that definition. Factors like FOV could also affect their perception. Realistically, any height (within reason) would work if the maps were built for that scale. The issue is primarily aesthetic, so perception needs to be accounted for.

**Comment by SniperGoth** [comment]
Well, my personal height is around 1,95 cm, and the  scale from 1.6 and earlier is far from close to how my perspective is.
Felt like i was a midget (same thing happens with sauer's playerscale, but that's off-topic), didn't feel right.
Now the current scale really feels better and more "realistic", to be honest, so i hope we keep it.

**Comment by Friedslick6** [comment]
That makes perfect sense, your eyes would line up near-perfectly with the current setting. But your height is an outlier according to statistical averages.
I'm 175cm, with an estimated eye-to-monitor calculated FOV of 95. I think being able to look over walls that are supposed to look 2 metres high is disorientating. I only found the original height slightly shorter than it should have been.
I think the height should be decided by either the average height of country of which the majority of RE IP addresses currently originate from, or by the global average height of 170cm.

**Comment by brian70123475** [comment]
Regardless, the textures are still inaccurate. As Dziq was pointing out in an editing session, a player is two meters high even while crouching.

![](https://image.ibb.co/iwKnQJ/20180613202324.png)

**Comment by Dziq84** [comment]
I think its because animation of players crouching is out of place, in game you crouch lower that animation is showing.. 
This situation can be observed when you hide behind a obstacle, but other player still is able to see your head, which do not take any damage then.. we just need someone good in animations to fix that...  or place fpp camera a little more upwards...

**Comment by Friedslick6** [comment]
Dziq is right. The current lowest crouch height is 165.625cm and that animation is way off.

**Comment by Dziq84** [comment]
currently third person crouch animation looks like that:
![20180614123318](https://user-images.githubusercontent.com/13541407/41407415-a3e09044-6fcf-11e8-82d5-7e240fec5eb5.jpg)
and the same seen from FPP:
![20180614123312](https://user-images.githubusercontent.com/13541407/41407538-05b45c74-6fd0-11e8-854b-e0da7f45852c.jpg)
This disproportion resulting in other players in situation which theay are able to see your head, but can't make any damage when shooting at it


What if we replace crouch animation with proper one?:  
![20180614122837](https://user-images.githubusercontent.com/13541407/41407669-6cf189fc-6fd0-11e8-9417-0a357732d0d0.jpg)
it is out of question or maybe good idea?

**Comment by qreeves** [comment]
@Dziq Yes, please!

**Comment by Friedslick6** [comment]
This crouch animation is a great improvement, and I don't think it looks unnatural morphing between other crouch animations either.
That aside, I still hold contention on the height of the player for previously mentioned reasons. Further, I think there needs to be a stronger correlation between player size and parkour abilities as compromise for the related gameplay issues.

**Comment by qreeves** [comment]
Implemented new animation and the height adjustments in red-eclipse/base@679f0b0
