### ISSUE TITLE
Install Red Eclipse from Repositories on Ubuntu 18.04

### ISSUE THREAD

**Issue by lope** [redeclipse/world#52]
Hey guys,
I'm testing Ubuntu 18.04 dev version.

Under [Unofficial builds, in the installation wiki](https://redeclipse.net/wiki/How_to_Install_Red_Eclipse#Unofficial_Builds)
I see On the [Red Eclipse Apt Repos page](https://software.opensuse.org/download/package?project=home:TheAssassin:RedEclipse&package=redeclipse) there is currently a choice of 16.04 and 17.04. Which one should I try for running on 18.04?

**Comment by IceflowRE** [comment]
> These packages are created by third parties and aren't officially supported by the Red Eclipse project.

Furthermore why do you dont use the standard installation for Linux or https://redeclipse.net/wiki/How_to_Install_Red_Eclipse#AppImage?
If you can use a 16.04 or 17.04 version on an 18.04 i can not answer to you.

**Comment by lope** [comment]
Thanks, will try
