### ISSUE TITLE
 ffs22

### ISSUE THREAD

**Issue by molexted** [redeclipse/world#6]
![20190331223244](https://user-images.githubusercontent.com/23445929/55305467-7bcb4700-5405-11e9-81a4-50a02dc619a6.png)
![20190331223228](https://user-images.githubusercontent.com/23445929/55305468-7bcb4700-5405-11e9-9f14-a0918c4cb76e.png)
![20190331223212](https://user-images.githubusercontent.com/23445929/55305469-7bcb4700-5405-11e9-8702-d5a3f5c30060.png)
![20190331223144](https://user-images.githubusercontent.com/23445929/55305470-7c63dd80-5405-11e9-9f41-d01bc1ff67f4.png)

r262: [ffs22.zip](https://github.com/red-eclipse/world/files/1993649/ffs22.zip)
r266: [ffs22.zip](https://github.com/red-eclipse/world/files/2064727/ffs22.zip)
r280: [ffs22.zip](https://github.com/red-eclipse/world/files/2614257/ffs22.zip)
r282: [ffs22.zip](https://github.com/red-eclipse/world/files/3027889/ffs22.zip)

now with envmapped glass
fixed decals
prettier windowframes
nice stairs 
mapeffects support

22kt/31kv
106 entities
32 lights

it is:
playable
themed
optimized
day/night

it is missing:
details
sound

WTFPL v2.0

**Comment by Dziq84** [comment]
it is finished already?

**Comment by molexted** [comment]
r202: better windows

**Comment by acerspyro** [comment]
it is finished already?

**Comment by IceflowRE** [comment]
Maybe create a 'WIP' label?

**Comment by acerspyro** [comment]
*bump*

Oh. Wait.

**Comment by molexted** [comment]
r235

nice stairs everywhere
light fixes
nicer beams

**Comment by molexted** [comment]
r250

more nice stairs
nicer ceilings
moved grenade spawn
larger catwalk

**Comment by molexted** [comment]
r255

better ceilings
more nicer stairs
fixed alpha
optimizations

**Comment by acerspyro** [comment]
it is finished already?

**Comment by qreeves** [comment]
Now in master for testing purposes as of red-eclipse/base@8a3ec68e75e1296f19aad884668b6719f2712d91
