### ISSUE TITLE
Um can i gets some maps

### ISSUE THREAD

**Issue by sharkigames** [redeclipse/world#74]
maps... there aren't many maps that are huge i mean they are big buuut not for my liking i want huge like battle royale huge for survivor mode i liked battle royale games for a long time but i dont want to write them down i need maps that are large

**Comment by IceflowRE** [comment]
There are some really huge maps, like [Dawn](https://www.redeclipse.net/docs/maps/Dawn) ([dawn.zip](https://github.com/red-eclipse/world/files/2303922/dawn.zip)), but really large maps like you know from PUBG arent available, because the engine cannot handle those huge maps.

**Comment by shirepirate** [comment]
largest map i've ever played on in RE was some custom map from another sauer fork someone was making. think it was featured on mapping hell old site. map may have even been called "hell." was absolutely huge

**Comment by qreeves** [comment]
Yeah, what we lack is any sort of LOD system that could properly reduce anything rendered at a distance for performance, the tenet of the engine was always arena type maps that make good use of occlusion to obscure things in order for it to be entirely culled.

It's a huge undertaking that'd have very little benefit to the current game (as large maps always play terribly in regular game modes). This isn't really just about the code, but also the content that would need to be generated to accommodate such a feature, and we're barely getting by just getting the content we absolutely need.

I really need to get around to evaluating the content in the dev version and highlighting the things that need doing. It has turned into a developer-hack hell...
