### ISSUE TITLE
Biggy (Lucifer) should be banned

### ISSUE THREAD

**Issue by Matadula** [redeclipse/world#75]
Hi. I’m Alxa and i came here to report a player called "Biggy" (now goes under the name "Lucifer"). He has been temporarily kicked/muted/banned several times for different reasons since he started playing. You guys may remember this: https://redeclipse.net/oldforum/viewtopic.php?f=7&t=509

The main reason i want to report him is because his behavior got even more toxic in the past year. Back then only Spanish speaking people had to deal with him (i believe he is one of the reasons the Spanish RE community is so small, he scared everybody away). But now he targets new people that don’t know how to deal with him (old players just ignore him).

Why he should get banned:

1.  Insults everyone without any kind of provocation (mainly new people)
2. Tries to start fights between players with pure lies (telling player "A" that player "B" said something mean about him for example).
3. Griefs other people creations on edit servers.
4. Tries to get other people banned without a reason. Last month he tried to get "Damian Things" banned by "Dziq" (by the way Dziq, if you are reading this, be wary with Biggy (lucifer). he's just pretending to be your friend so you ban people for him).
5. He killed the clan "GTC" (funded by "Tropper", it was full of new people), by pretending to be their friend and then starting drama between their members.

And on top of that:

6. He teamkills often.
7. Reveals position and health of his own teammates on "Survivor"
8. He often grabs his flag and takes it to the enemy base.

The guy is just a waste of bandwidth and i think he should be banned permanently. He doesn't even come here to play, he just comes here to troll (if you mute him, he leaves). Several players can back me up on this. I have seen Yeatta and F41k ban/mute him several times.

A demo (i will get more in the future):

[20180822052818.zip](https://github.com/red-eclipse/world/files/2316469/20180822052818.zip)

On 6:50 Tropper tells me that Biggy (Lucifer) killed his clan. Then Biggy starts insulting him and everybody on the server for no reason

I believe this game needs a mod that speaks Spanish to deal with this kind of situations (Biggy would have been banned since 2014 if this was the case). I may be up for the task if someone backs me up.

**Comment by molexted** [comment]
For what it's worth, they don't appear to be the same person; Biggy has a Geforce 9500GT and Lucifer has a HD 7570. Lucifer is definitely a nuisance, but I haven't seen Biggy around too much recently. 

One of the problems with not requiring an account to play is that people with dynamic IPs don't really get banned, since their IP changes frequently. Biggy had been put on the ban list several times and yet he (the real one, who logged in with his account) was still able to join a couple days ago.

I'll see what I can do.

**Comment by SniperGoth** [comment]
To be honest i never thought both were the same person to begin with.
Sometimes lucifer is hard to deal with, but i haven't been dealing with him the last weeks (im lurking more around 1.9 and other things).
Next time i see him i'll give him a fair warning .

**Comment by IceflowRE** [comment]
Another option is to inform or better ping us in IRC/ Discord if he/ they make trouble, that we can take a look. Dealing with it after is a bit harder though, also under the aspect of dynamical ip's.

**Comment by Goldenbrain1** [comment]
By the way those who banned him a few times know he has got a VPN
Better letting that to local moderation

**Comment by Matadula** [comment]
Oh no no, he is Biggy, believe me. He only got another computer.

**Comment by molexted** [comment]
Banned in iplist.cfg for probably ten minutes, since he's just going to change his IP. There isn't a whole lot we can do besides slapping his IP in the banlist file as often as we find it, which is a problem with not requiring authentication to play online. Only by making accounts mandatory would it be possible to eradicate his presence against his will.

**Comment by nonoesimposible** [comment]
If I understand correctly, the reason we don't require authentication to play is that it takes a lot of time and effort to check out a player account by hand, correct?

Is there any way we could speed this up? For instance, I'd be happy to volunteer the time to review these applications, and I think a couple other dedicated players would too, but then, of course, we wouldn't have the knowledge or qualifications to make such important decisions.

**Comment by IceflowRE** [comment]
@Matadula I dont see what forced accounts would change. You can still make a new one whenever you want.
