### ISSUE TITLE
We're headed to Steam and giving away beta keys

### ISSUE THREAD

**Issue by qreeves** [redeclipse/world#83]
As part of [our collaboration with OKLetsPlay](https://github.com/red-eclipse/world/issues/79), we decided the best way to handle authentication was to address the elephant in the room: Red Eclipse should be on Steam! That's right, we're finally doing it thanks to a little help from our friends 😄 

As it stands, I've paid our fee, uploaded a build, and gotten our initial [Store Page](https://store.steampowered.com/app/967460/Red_Eclipse/) reviewed. We are now officially marked as "Coming Soon". As this is a preview of the upcoming v2 release, I won't be pushing a build to the public until all the necessary work is done (we want to make a good first impression). For now, the only way to play Red Eclipse on Steam is with a beta tester key.

So far, I've distributed keys to the relevant developers and general community, as these are the first people I wanted to have access to the game. Without all of these people, Red Eclipse wouldn't be the fantastic project and community it is today, and this was my way of showing them some appreciation for their support. I'm truly proud of you all, each and every person thanked me.

You're probably wondering where you can get your key! Well, I've ordered another 100 keys for the general public to test the beta builds prior to the official release, and I'm giving them all away in a competition. To enter, [link your Steam ID to your Red Eclipse account](https://hq.redeclipse.net/account), if you don't already have an account, you can [register for one now](https://redeclipse.net/apply) and link your Steam ID at the same time.

- No access is granted to your Steam account, we only store your ID.
- We only use the ID to pair your Red Eclipse account when you use Steam to play.
- Competition ends Saturday the 10th of November 2018 10:00 UTC.
- Winners will be picked at random from a list of all accounts that have a Steam ID registered.
- Winners will be notified by email using the details associated with their _Red Eclipse_ account.

Need your Steam ID?

- Go to [steamcommunity.com](https://steamcommunity.com/).
- Click your profile picture at the top right.
- In the right hand navigation area, scroll down to find "Permalink".
- Your ID is the huge number at the end of this URL.

![steamcommunity](https://user-images.githubusercontent.com/3297929/47961959-910f9580-e060-11e8-96f3-48ecdfde1ac6.jpg)

If you can't figure that out, try:

- Go to [steamid.io](https://steamid.io/) and sign in with Steam.
- When you return back to the website, click your profile icon.
- Your ID is listed under "steamID64". 

![steamidio](https://user-images.githubusercontent.com/3297929/47960054-6fea7d00-e03f-11e8-81bb-127020548979.jpg)

**Comment by shirepirate** [comment]
great news!

**Comment by faergeek** [comment]
Is there any possibility to make it cost however you like, e.g. donation?

**Comment by qreeves** [comment]
@faergeek Unfortunately, doing it that way counts as income for which I should probably register a business, and I'm trying to avoid that because this is just a hobby and the paperwork is a nightmare. You can do proper "gift" donations at https://redeclipse.net/donate

**Comment by faergeek** [comment]
Very long form, so I just signed up on patreon :-)

**Comment by qreeves** [comment]
Long? It should look like this:
![image](https://user-images.githubusercontent.com/3297929/48057223-36f90680-e1ff-11e8-9dcc-806efedf1ed4.png)

**Comment by faergeek** [comment]
I chose card and there appeared all kinds of fields like country, address, card number, which food is my favourite etc. xD

**Comment by faergeek** [comment]
I just don't use PayPal too much. I don't have my current card there

**Comment by faergeek** [comment]
BTW, is there any merch about red eclipse, would like to buy something :-)

**Comment by qreeves** [comment]
Never been popular enough to even consider merchandise, but things are picking up so there's always a possibility.

**Comment by faergeek** [comment]
There's no need to be popular for that. It's just too easy for people to donate by buying some merch. I know at least a few musical bands which crowdfund album/clip recording like that and they get more money than needed very often.

**Comment by faergeek** [comment]
And they're still more or less underground

**Comment by faergeek** [comment]
There are ready made solutions, you don't even need to make your own design. People buy any merch they like and support you, giving you some money (not sure how many) from that and people even can use their own design for T-shirt or something like that, doesn't matter. Will try to investigate later more concrete options.

**Comment by faergeek** [comment]
Hmmm, the thing I was talking about with ready made merch and website is Russian only. Then I took a brief look at https://www.hellomerch.com/, I think it's more or less what's needed. Here's the list where you can look yourself https://support.google.com/youtube/answer/6083754?hl=en

**Comment by nonoesimposible** [comment]
Maybe this discussion should continue in a new issue. It no longer seems to be about Steam.

**Comment by bonifarz** [comment]
Hey quin, congrats for this move. I admit I have been away for a while, and I never was on Steam myself, but I see your efforts and the great potential. So I hope that everything goes well with the RE2.0 development and that the launch on Steam will be a success. I'm aware that some indie games have attracted lots of attention and popularity this way. So I wish you all the best for this awesome game you have created over all the years, and for its community as well.
