### ISSUE TITLE
Nerf the flamethrower?

### ISSUE THREAD

**Issue by CheezerMcNeezer** [redeclipse/world#90]
Flamethrower is super OP, just downloaded this game, picked up the flameboi, and went at least 20/2 in each game. I am by no means good at fps games so itg makes me think: "Hey what an unbalanced weapon"

**Comment by IceflowRE** [comment]
If you just downloaded the game i think you refer to the `stable` version?
Better try the development version, because there many things changed.
https://redeclipse.net/wiki/Obtain_development_version
If you use the steam version, you can get the development version there too.

**Comment by molexted** [comment]
Also see https://github.com/red-eclipse/base/issues/838 for the current discussion on 2.0 weapon balance
