### ISSUE TITLE
hi there guys i made A cartoon and sent it with quinn

### ISSUE THREAD

**Issue by eaeaivjmga88** [redeclipse/world#98]
so it 's me, trooper and beha at the first seen and the last sequence it's lee green suti withbue and blue quinn and acer yeatta the pink one -_-. so anyway quinn enjoy XD

**Comment by SniperGoth** [comment]
So... where is it?

**Comment by Dziq84** [comment]
this must be another joke xD

**Comment by eaeaivjmga88** [comment]
this is to u beloved -_- acer eat your heart i gave my word and i completed here's cartoon. quinn did it we can add more.i have the ability to make a cartoon episode each week
https://www.dailymotion.com/video/x73sdj2

**Comment by Dziq84** [comment]
lol !     I did not expected such good quality and plot, waiting for more...

**Comment by eaeaivjmga88** [comment]
okay guys look give me ideas, hey dziq how about we hook up and we use your voice for your part in the first episode. if any of u got good ideas i'm happy to hear them. oh yeah look going to put down the video going to refurbish and remake it make it better ;D. so i take it down and in A week or so put it again. oh yeah quinn pls bro send an e-mail pls i 've been looking for u r email for 2 days and coulnd't send u the video. u can see my e-mail . so before anyone else u can see my artwork and give u previews and share your opinion.

**Comment by Dziq84** [comment]
I don't think this is good idea to use my voice there, I will look at my timetable but now Im involved in just too much stuff out here so..  maybe in future episodes ;p
